#Project Info
info:
  app:
    name: Config Client Sample
    description: Config Client Sample
    version: 0.0.1

server:
  port: 15995
  tomcat:
    connection-timeout: 10s
    threads:
      max: 500
    remoteip:
      protocol-header: X-Forwarded-Proto
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true

spring:
  application:
    name: "app-1"
  http:
    mvc:
      servlet:
        load-on-startup: 1